<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-EG28T0P" failures="2" tests="10" name="Surefire test" time="34.848" errors="0" timestamp="2024-03-28T12:50:47 IST">
  <testcase classname="api.test.DatadrivenTest" name="testPostUser" time="7.447"/>
  <testcase classname="api.test.DatadrivenTest" name="testPostUser" time="3.577"/>
  <testcase classname="api.test.DatadrivenTest" name="testPostUser" time="2.142"/>
  <testcase classname="api.test.DatadrivenTest" name="testDeleteUserbyName" time="3.446"/>
  <testcase classname="api.test.DatadrivenTest" name="testDeleteUserbyName" time="2.04"/>
  <testcase classname="api.test.DatadrivenTest" name="testDeleteUserbyName" time="1.723"/>
  <testcase classname="api.test.UserTest" name="testPostUser" time="1.929"/>
  <testcase classname="api.test.UserTest" name="testGetUserByname" time="2.266"/>
  <testcase classname="api.test.UserTest" name="testUpdateUserbyName" time="1.953">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at api.test.UserTest.testUpdateUserbyName(UserTest.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateUserbyName -->
  <testcase classname="api.test.UserTest" name="testDeleteUserbyName" time="2.495">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at api.test.UserTest.testDeleteUserbyName(UserTest.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserbyName -->
</testsuite> <!-- Surefire test -->
